# backend/app/services/pdf_generator.py

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import inch
from datetime import datetime
import os

def generate_report(prediction_record: dict, output_path: str):
    """
    Generates a PDF report for a single prediction.
    """

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50
    )

    styles = getSampleStyleSheet()
    story = []

    # ---------------- TITLE ----------------
    story.append(Paragraph("<b>CanBridge – Cancer Screening Report</b>", styles["Title"]))
    story.append(Spacer(1, 0.3 * inch))

    # ---------------- METADATA ----------------
    created_at = datetime.fromisoformat(prediction_record["created_at"])
    story.append(Paragraph(f"<b>Date:</b> {created_at.strftime('%d %b %Y, %I:%M %p')}", styles["Normal"]))
    story.append(Paragraph(f"<b>Cancer Type:</b> {prediction_record['cancer_type'].capitalize()}", styles["Normal"]))
    story.append(Spacer(1, 0.2 * inch))

    # ---------------- RESULT ----------------
    story.append(Paragraph("<b>Prediction Result</b>", styles["Heading2"]))
    story.append(Paragraph(
        f"Prediction: <b>{prediction_record['prediction']}</b>",
        styles["Normal"]
    ))
    story.append(Paragraph(
        f"Confidence Score: <b>{round(prediction_record['confidence'] * 100, 2)}%</b>",
        styles["Normal"]
    ))
    story.append(Spacer(1, 0.3 * inch))

    # ---------------- GUIDANCE ----------------
    story.append(Paragraph("<b>Supportive Care & Lifestyle Guidance</b>", styles["Heading2"]))

    if "No Tumor" in prediction_record["prediction"]:
        guidance_text = """
        This screening result did not indicate the presence of cancer.
        <br/><br/>
        It is recommended to maintain a healthy lifestyle through balanced nutrition,
        regular physical activity, adequate sleep, and routine medical check-ups.
        <br/><br/>
        Avoid smoking, excessive alcohol consumption, and prolonged exposure to environmental pollutants.
        """
    else:
        guidance_text = """
        This screening result suggests the presence of a condition that requires
        further medical evaluation.
        <br/><br/>
        It is important to consult a qualified healthcare professional as soon as possible.
        Maintaining proper nutrition, hydration, emotional support, and avoiding harmful habits
        such as smoking can help support overall well-being during further assessment.
        """

    story.append(Paragraph(guidance_text, styles["Normal"]))
    story.append(Spacer(1, 0.3 * inch))

    # ---------------- DISCLAIMER ----------------
    story.append(Paragraph("<b>Important Disclaimer</b>", styles["Heading2"]))
    story.append(Paragraph(
        "This report is generated by an AI-assisted screening system for informational purposes only. "
        "It is not a medical diagnosis and should not be used as a substitute for professional medical advice.",
        styles["Normal"]
    ))

    # Build PDF
    doc.build(story)
