# backend/app/services/pdf_generator.py

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import inch
from datetime import datetime
import os

from app.services.guidance_generator import generate_guidance


def generate_report(prediction_record: dict, output_path: str):
    """
    Generates a PDF report for a single prediction,
    including GenAI-generated supportive care guidance.
    """

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50
    )

    styles = getSampleStyleSheet()
    story = []

    # ---------------- TITLE ----------------
    story.append(Paragraph("<b>CanBridge – Cancer Screening Report</b>", styles["Title"]))
    story.append(Spacer(1, 0.3 * inch))

    # ---------------- METADATA ----------------
    created_at = datetime.fromisoformat(prediction_record["created_at"])
    story.append(Paragraph(
        f"<b>Date:</b> {created_at.strftime('%d %b %Y, %I:%M %p')}",
        styles["Normal"]
    ))
    story.append(Paragraph(
        f"<b>Cancer Type:</b> {prediction_record['cancer_type'].capitalize()}",
        styles["Normal"]
    ))
    story.append(Spacer(1, 0.2 * inch))

    # ---------------- RESULT ----------------
    story.append(Paragraph("<b>Prediction Result</b>", styles["Heading2"]))
    story.append(Paragraph(
        f"Prediction: <b>{prediction_record['prediction']}</b>",
        styles["Normal"]
    ))
    story.append(Paragraph(
        f"Confidence Score: <b>{round(prediction_record['confidence'] * 100, 2)}%</b>",
        styles["Normal"]
    ))
    story.append(Spacer(1, 0.3 * inch))

    # ---------------- GENAI GUIDANCE ----------------
    story.append(Paragraph("<b>Supportive Care & Lifestyle Guidance</b>", styles["Heading2"]))

    try:
        guidance_text = generate_guidance(
            cancer_type=prediction_record["cancer_type"],
            prediction=prediction_record["prediction"]
        )
    except Exception as e:
        guidance_text = (
            "Supportive guidance could not be generated at this time. "
            "Please consult a healthcare professional for further advice."
        )

    # Convert plain text into PDF-safe paragraphs
    for paragraph in guidance_text.split("\n\n"):
        story.append(Paragraph(paragraph.strip(), styles["Normal"]))
        story.append(Spacer(1, 0.15 * inch))

    # ---------------- DISCLAIMER ----------------
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("<b>Important Disclaimer</b>", styles["Heading2"]))
    story.append(Paragraph(
        "This report is generated by an AI-assisted screening system for informational purposes only. "
        "It does not provide medical advice, diagnosis, or treatment and should not be used as a "
        "substitute for consultation with a qualified healthcare professional.",
        styles["Normal"]
    ))

    # Build PDF
    doc.build(story)
